doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Message:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Message/Domain'
                prefix: 'App\Message\Domain'
                alias: Message
            User:
                is_bundle: false
                dir: '%kernel.project_dir%/src/User/Domain'
                prefix: 'App\User\Domain'
                alias: User
when@test:
    doctrine:
        dbal:
            dbname_suffix: ''

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
